MOOD_PROFILES = {
    "happy": {
        "genres": ["pop", "dance", "funk", "disco", "indie-pop"],
        "target_valence": 0.8,
        "min_valence": 0.6,
        "target_energy": 0.7,
        "min_energy": 0.5,
        "description": "Upbeat, cheerful, feel-good vibes",
        "search_descriptors": ["upbeat", "feel good", "happy", "cheerful"],
    },
    "sad": {
        "genres": ["indie", "acoustic", "singer-songwriter", "pop", "soul"],
        "target_valence": 0.2,
        "max_valence": 0.4,
        "target_energy": 0.3,
        "max_energy": 0.5,
        "description": "Melancholic, emotional, reflective",
        "search_descriptors": ["sad", "heartbreak", "yearning", "crying"],
    },
    "energetic": {
        "genres": ["rock", "edm", "hip-hop", "metal", "electronic"],
        "target_valence": 0.6,
        "min_valence": 0.4,
        "target_energy": 0.9,
        "min_energy": 0.7,
        "max_acousticness": 0.1,
        "description": "High-intensity, pumped up, powerful",
        "search_descriptors": ["hype", "pump up", "workout", "intense"],
    },
    "chill": {
        "genres": ["ambient", "lo-fi", "jazz", "r-n-b", "downtempo"],
        "target_valence": 0.5,
        "target_energy": 0.3,
        "max_energy": 0.5,
        "min_acousticness": 0.3,
        "description": "Relaxed, smooth, laid-back",
        "search_descriptors": ["chill", "relaxing", "smooth", "lofi"],
    },
    "angry": {
        "genres": ["metal", "punk", "hard-rock", "hardcore", "industrial"],
        "target_valence": 0.3,
        "max_valence": 0.45,
        "target_energy": 0.9,
        "min_energy": 0.7,
        "max_acousticness": 0.1,
        "description": "Aggressive, intense, raw emotion",
        "search_descriptors": ["aggressive", "rage", "angry", "heavy"],
    },
    "nostalgic": {
        "genres": ["indie", "folk", "alternative", "soft-rock", "acoustic"],
        "target_valence": 0.4,
        "max_valence": 0.6,
        "target_energy": 0.3,
        "max_energy": 0.5,
        "description": "Wistful, reflective, bittersweet memories",
        "search_descriptors": ["throwback", "nostalgic", "classic", "old school"],
    },
    "anxious": {
        "genres": ["ambient", "electronic", "experimental", "indie"],
        "target_valence": 0.3,
        "max_valence": 0.5,
        "target_energy": 0.6,
        "description": "Restless, uneasy, on edge",
        "search_descriptors": ["dark", "tense", "atmospheric", "uneasy"],
    },
    "cozy": {
        "genres": ["lo-fi", "indie-folk", "acoustic", "jazz", "bedroom-pop"],
        "target_valence": 0.6,
        "min_valence": 0.4,
        "target_energy": 0.25,
        "max_energy": 0.45,
        "min_acousticness": 0.5,
        "description": "Warm, comfortable, intimate vibes",
        "search_descriptors": ["cozy", "warm", "soft", "gentle"],
    },
    "melancholic": {
        "genres": ["indie", "alternative", "shoegaze", "dream-pop", "slowcore"],
        "target_valence": 0.2,
        "max_valence": 0.35,
        "target_energy": 0.3,
        "max_energy": 0.5,
        "description": "Deep sadness, beautiful sorrow, poetic darkness",
        "search_descriptors": ["melancholy", "depressing", "yearning", "sadness", "crying"],
    },
    "sensual": {
        "genres": ["dark-pop", "trap", "alternative-r-n-b", "r-n-b"],
        "target_valence": 0.40,
        "target_energy": 0.70,
        "min_energy": 0.40,
        "description": "Seductive, sultry, intimate heat & dark pop",
        "search_descriptors": ["toxic", "explicit", "dark r&b", "seductive", "sensual"],
    },
}

# Flexible association map for unconventional/slang/contextual mood inputs.
# These are checked as a fallback when primary MOOD_KEYWORDS don't match.
# Maps any word/phrase → mood ID.
MOOD_ASSOCIATIONS = {
    # Romantic / Sensual / Sexual → sensual mood
    "hot": "sensual",
    "horny": "sensual",
    "frisky": "sensual",
    "turned on": "sensual",
    "sensual": "sensual",
    "romantic": "sensual",
    "in love": "happy",
    "lovesick": "melancholic",
    "heartbreak": "melancholic",
    "heartbroken": "melancholic",
    "love": "happy",
    "crushing": "happy",
    "butterflies": "happy",
    "desire": "sensual",
    "lustful": "sensual",
    "passionate": "sensual",
    "intimate": "sensual",
    "steamy": "sensual",
    "flirty": "sensual",
    "seductive": "sensual",
    "late night": "sensual",
    "slow jam": "sensual",
    "body": "sensual",
    "touch": "sensual",
    "bedroom": "sensual",
    "after dark": "sensual",

    # Party / Social
    "party": "energetic",
    "rave": "energetic",
    "club": "energetic",
    "dance": "energetic",
    "turn up": "energetic",
    "pregame": "energetic",
    "shots": "energetic",
    "drunk": "happy",
    "tipsy": "happy",
    "wasted": "sad",
    "hangover": "melancholic",
    "celebrate": "happy",
    "slay": "energetic",
    "queen": "happy",
    "boss": "energetic",

    # Work / Productivity
    "grinding": "energetic",
    "hustle": "energetic",
    "working": "chill",
    "studying": "chill",
    "focus": "chill",
    "productive": "energetic",
    "deadline": "anxious",
    "exam": "anxious",
    "burnt out": "melancholic",
    "tired": "chill",
    "exhausted": "sad",
    "bored": "chill",
    "lazy": "cozy",

    # Weather / Atmosphere
    "rainy": "melancholic",
    "sunny": "happy",
    "cold": "cozy",
    "winter": "cozy",
    "summer": "happy",
    "storm": "angry",
    "cloudy": "melancholic",
    "foggy": "nostalgic",
    "night": "chill",
    "sunrise": "happy",
    "sunset": "nostalgic",
    "midnight": "melancholic",

    # Life events
    "breakup": "melancholic",
    "wedding": "happy",
    "funeral": "melancholic",
    "graduation": "happy",
    "birthday": "happy",
    "moving on": "energetic",
    "starting over": "nostalgic",
    "new beginning": "happy",
    "road trip": "energetic",
    "traveling": "happy",
    "adventure": "energetic",
    "home alone": "cozy",
    "cooking": "cozy",
    "bath": "chill",
    "spa": "chill",
    "gym": "energetic",
    "working out": "energetic",
    "running": "energetic",
    "walking": "chill",

    # Internet culture
    "main character": "happy",
    "villain era": "angry",
    "toxic": "angry",
    "red flag": "anxious",
    "green flag": "happy",
    "sus": "anxious",
    "ghosted": "melancholic",
    "simping": "sad",
    "rizz": "happy",
    "delulu": "happy",
    "unhinged": "energetic",
    "feral": "energetic",
    "venting": "angry",
    "ranting": "angry",
    "crying in the club": "sad",
    "touch grass": "chill",

    # Filipino slang / expressions
    "kilig": "happy",
    "gigil": "happy",
    "tampo": "sad",
    "sawi": "sad",
    "hugot": "melancholic",
    "yearning": "melancholic",
    "lss": "nostalgic",
    "walwal": "energetic",
    "chill lang": "chill",
    "petmalu": "energetic",
    "lodi": "energetic",
    "charot": "happy",
    "nakakaloka": "energetic",
    "grabe": "energetic",
    "malungkot": "sad",
    "masaya": "happy",
    "galit": "angry",
    "kaba": "anxious",
    "miss ko na": "nostalgic",
}

MOOD_KEYWORDS = {
    "happy": [
        # Classic happiness
        "happy",
        "joyful",
        "excited",
        "great",
        "amazing",
        "wonderful",
        "cheerful",
        "delighted",
        "fantastic",
        "awesome",
        "good",
        "glad",
        # Modern/slang
        "vibing",
        "lit",
        "fire",
        "blessed",
        "thriving",
        "winning",
        "hyped",
        "stoked",
        "pumped",
        "living my best life",
        "on cloud nine",
        "slaps",
        "bussin",
        "goated",
        "no cap",
        "W",
        "based",
        "main character energy",
        "living the dream",
        "peak",
        "feeling good",
        "riding high",
        "absolutely buzzing",
        "over the moon",
        "walking on air",
        "grinning",
        # Subtle/nuanced
        "content",
        "grateful",
        "optimistic",
        "hopeful",
        "bright",
        "lowkey happy",
        "pretty good",
        "doing well",
        "can't complain",
        "feeling myself",
        "in a good place",
        "uplifted",
        "elated",
    ],
    "sad": [
        # Classic sadness
        "sad",
        "down",
        "unhappy",
        "upset",
        "lonely",
        "blue",
        "crying",
        "tears",
        # Modern/slang
        "big sad",
        "in my feels",
        "soft",
        "emo",
        "hurt",
        "broken",
        "feeling some type of way",
        "not okay",
        "struggling",
        "meh",
        "blah",
        "whatever",
        "don't care anymore",
        "apathetic",
        "listless",
        "flat",
        "going through it",
        "rough patch",
        "tough time",
        "not vibing",
        "off",
        "drained",
        "worn down",
        "defeated",
        "crushed",
        # Nuanced emotions
        "empty",
        "numb",
        "lost",
        "disconnected",
        "fragile",
        "vulnerable",
        "aching",
        "homesick",
        "dejected",
        "downcast",
        "feeling off",
        "not myself",
        "low",
        "drained emotionally",
        "emotionally exhausted",
    ],
    "energetic": [
        # Classic energy
        "energetic",
        "pumped",
        "hyped",
        "motivated",
        "active",
        "intense",
        "powerful",
        "strong",
        "driven",
        "fired up",
        "ready",
        "go",
        # Modern/slang
        "let's go",
        "amped",
        "wired",
        "on one",
        "turnt",
        "hype",
        "beast mode",
        "locked in",
        "in the zone",
        "ready to run",
        "cracked",
        "built different",
        "going hard",
        "no sleep",
        "grinding",
        "on fire",
        "popping off",
        "going crazy",
        "energized",
        "revved up",
        "jacked up",
        "ready to go",
        # Nuanced
        "restless",
        "charged",
        "electric",
        "buzzing",
        "focused",
        "determined",
        "unstoppable",
        "alive",
        "invigorated",
        "can't sit still",
        "need to move",
        "full of energy",
        "wired up",
    ],
    "chill": [
        # Classic relaxation
        "chill",
        "relaxed",
        "calm",
        "peaceful",
        "mellow",
        "laid-back",
        "easy",
        "comfortable",
        "tranquil",
        "serene",
        "zen",
        "smooth",
        # Modern/slang
        "vibing",
        "lowkey",
        "unbothered",
        "no worries",
        "taking it easy",
        "in my zone",
        "just existing",
        "floating",
        "coasting",
        "cruising",
        "easygoing",
        "go with the flow",
        "whatever happens",
        "no stress",
        "all good",
        "it is what it is",
        "taking life slow",
        "no rush",
        "just vibes",
        "relaxing",
        "netflix and chill",
        "lazy day",
        "me time",
        # Nuanced
        "contemplative",
        "meditative",
        "at ease",
        "balanced",
        "centered",
        "quiet",
        "still",
        "grounded",
        "present",
        "mindful",
        "lazy",
        "sleepy",
        "drowsy",
        "lounging",
        "resting",
        "winding down",
        "decompressing",
        "chilling out",
    ],
    "angry": [
        # Classic anger
        "angry",
        "mad",
        "furious",
        "frustrated",
        "annoyed",
        "irritated",
        "pissed",
        "rage",
        "upset",
        "bitter",
        "hostile",
        "aggressive",
        # Modern/slang
        "salty",
        "triggered",
        "livid",
        "heated",
        "over it",
        "done",
        "fed up",
        "can't even",
        "so done",
        "had enough",
        "pissed off",
        "ticked off",
        "steaming",
        "boiling",
        "seeing red",
        "done with this",
        "can't take it",
        "absolute rage",
        "furious",
        "livid af",
        "mad as hell",
        # Nuanced
        "resentful",
        "vindictive",
        "vengeful",
        "indignant",
        "outraged",
        "seething",
        "fuming",
        "irate",
        "wrathful",
        "incensed",
        "burned out",
        "exhausted with",
        "tired of",
        "sick of",
        "at my limit",
        "about to snap",
        "losing it",
    ],
    "nostalgic": [
        "nostalgic",
        "throwback",
        "reminiscing",
        "missing",
        "old times",
        "back then",
        "used to",
        "remember when",
        "those days",
        "bittersweet",
        "wistful",
        "sentimental",
        "thinking of",
        "past",
        "memories",
        "longing",
        "yearning",
        "remembering",
        "the good old days",
        "flashback",
        "reminisce",
        "miss",
        "homesick",
        "pining",
        "looking back",
        "used to be",
        "miss the old days",
        "take me back",
        "simpler times",
        "when things were better",
        "childhood",
        "growing up",
        "wish I could go back",
        "those were the days",
    ],
    "anxious": [
        "anxious",
        "worried",
        "nervous",
        "stressed",
        "overwhelmed",
        "panicking",
        "freaking out",
        "on edge",
        "uneasy",
        "tense",
        "restless",
        "jittery",
        "antsy",
        "spiraling",
        "overthinking",
        "can't relax",
        "mind racing",
        "stressed out",
        "high strung",
        "paranoid",
        "fearful",
        "afraid",
        "scared",
        "terrified",
        "uncomfortable",
        "insecure",
        "uncertain",
        "doubt",
        "concern",
        "freaked",
        "losing my mind",
        "can't breathe",
        "panic attack",
        "anxiety attack",
        "chest tight",
        "hyperventilating",
        "doom scrolling",
        "catastrophizing",
        "what if",
        "rainy day vibes",
        "fireplace",
        "sweater weather",
        "tea and blankets",
        "soft lighting",
        "candlelit",
        "hibernating",
        "nesting",
        "staying in",
    ],
    "cozy": [
        "cozy",
        "comfy",
        "warm",
        "snug",
        "cuddled up",
        "blanket",
        "home",
        "safe",
        "soft",
        "gentle",
        "tender",
        "intimate",
        "wrapped up",
        "nestled",
        "tucked in",
        "hygge",
        "homebody",
        "comfort",
        "snuggled",
        "warm and fuzzy",
        "peaceful",
        "cocoon",
        "sanctuary",
        "haven",
        "sheltered",
        "protected",
    ],
    "melancholic": [
        "melancholic",
        "melancholy",
        "depressed",
        "depressing",
        "miserable",
        "heartbroken",
        "devastated",
        "grieving",
        "grief",
        "despair",
        "hopeless",
        "somber",
        "pensive",
        "brooding",
        "dark",
        "gloomy",
        "mournful",
        "sorrowful",
        "forlorn",
        "desolate",
        "bleak",
        "gray",
        "rainy day",
        "heavy",
        "tragic",
        "woeful",
        "doleful",
        "lugubrious",
        "cheerless",
        "dismal",
        "dreary",
        "morose",
        "sullen",
        "glum",
        "hollow",
        "heavy hearted",
        "existential",
        "questioning everything",
        "life is meaningless",
        "what's the point",
        "empty inside",
        "void",
        "abyss",
        "beautifully sad",
        "tragically beautiful",
        "poetic pain",
    ],
    "sensual": [
        "sensual",
        "seductive",
        "sultry",
        "hot",
        "horny",
        "frisky",
        "lustful",
        "desire",
        "passionate",
        "steamy",
        "flirty",
        "romantic",
        "intimate",
        "turned on",
        "body",
        "touch",
        "bedroom",
        "late night",
        "slow jam",
        "after dark",
        "temptation",
        "sexy",
        "alluring",
        "provocative",
        "tantalizing",
        "magnetic",
        "irresistible",
        "spicy",
        "heat",
        "tension",
        "chemistry",
        "skin",
        "whisper",
        "craving",
        "thirst",
        "thirsty",
    ],
}
