MOOD_PROFILES = {
    "happy": {
        "genres": ["pop", "dance", "funk", "disco", "indie-pop"],
        "target_valence": 0.7,  # High positivity
        "target_energy": 0.7,  # High energy
        "description": "Upbeat, cheerful, feel-good vibes",
    },
    "sad": {
        "genres": ["blues", "indie", "acoustic", "singer-songwriter", "soul"],
        "target_valence": 0.3,  # Low positivity
        "target_energy": 0.4,  # Low-medium energy
        "description": "Melancholic, emotional, reflective",
    },
    "energetic": {
        "genres": ["rock", "edm", "hip-hop", "metal", "electronic"],
        "target_valence": 0.6,
        "target_energy": 0.9,  # Very high energy
        "description": "High-intensity, pumped up, powerful",
    },
    "chill": {
        "genres": ["ambient", "lo-fi", "jazz", "r-n-b", "downtempo"],
        "target_valence": 0.5,
        "target_energy": 0.3,  # Very low energy
        "description": "Relaxed, smooth, laid-back",
    },
    "angry": {
        "genres": ["metal", "punk", "hard-rock", "hardcore", "industrial"],
        "target_valence": 0.3,
        "target_energy": 0.95,  # Maximum energy
        "description": "Aggressive, intense, raw emotion",
    },
    "nostalgic": {
        "genres": ["indie", "folk", "alternative", "soft-rock", "acoustic"],
        "target_valence": 0.4,
        "target_energy": 0.3,
        "description": "Wistful, reflective, bittersweet memories",
    },
    "anxious": {
        "genres": ["ambient", "electronic", "experimental", "indie"],
        "target_valence": 0.3,
        "target_energy": 0.6,
        "description": "Restless, uneasy, on edge",
    },
    "cozy": {
        "genres": ["lo-fi", "indie-folk", "acoustic", "jazz", "bedroom-pop"],
        "target_valence": 0.6,
        "target_energy": 0.2,
        "description": "Warm, comfortable, intimate vibes",
    },
    "melancholic": {
        "genres": ["indie", "alternative", "shoegaze", "dream-pop", "slowcore"],
        "target_valence": 0.2,
        "target_energy": 0.3,
        "description": "Deep sadness, beautiful sorrow, poetic darkness",
    },
}

MOOD_KEYWORDS = {
    "happy": [
        # Classic happiness
        "happy",
        "joyful",
        "excited",
        "great",
        "amazing",
        "wonderful",
        "cheerful",
        "delighted",
        "fantastic",
        "awesome",
        "good",
        "glad",
        # Modern/slang
        "vibing",
        "lit",
        "fire",
        "blessed",
        "thriving",
        "winning",
        "hyped",
        "stoked",
        "pumped",
        "living my best life",
        "on cloud nine",
        "slaps",
        "bussin",
        "goated",
        "no cap",
        "W",
        "based",
        "main character energy",
        "living the dream",
        "peak",
        "feeling good",
        "riding high",
        "absolutely buzzing",
        "over the moon",
        "walking on air",
        "grinning",
        # Subtle/nuanced
        "content",
        "grateful",
        "optimistic",
        "hopeful",
        "bright",
        "lowkey happy",
        "pretty good",
        "doing well",
        "can't complain",
        "feeling myself",
        "in a good place",
        "uplifted",
        "elated",
    ],
    "sad": [
        # Classic sadness
        "sad",
        "down",
        "depressed",
        "unhappy",
        "miserable",
        "upset",
        "heartbroken",
        "lonely",
        "blue",
        "melancholy",
        "crying",
        "tears",
        # Modern/slang
        "big sad",
        "in my feels",
        "soft",
        "emo",
        "hurt",
        "broken",
        "feeling some type of way",
        "not okay",
        "struggling",
        "meh",
        "blah",
        "whatever",
        "don't care anymore",
        "apathetic",
        "listless",
        "flat",
        "going through it",
        "rough patch",
        "tough time",
        "not vibing",
        "off",
        "drained",
        "worn down",
        "defeated",
        "crushed",
        # Nuanced emotions
        "empty",
        "numb",
        "hollow",
        "lost",
        "disconnected",
        "fragile",
        "vulnerable",
        "aching",
        "grieving",
        "homesick",
        "dejected",
        "somber",
        "gloomy",
        "downcast",
        "feeling off",
        "not myself",
        "heavy hearted",
        "low",
        "drained emotionally",
        "emotionally exhausted",
    ],
    "energetic": [
        # Classic energy
        "energetic",
        "pumped",
        "hyped",
        "motivated",
        "active",
        "intense",
        "powerful",
        "strong",
        "driven",
        "fired up",
        "ready",
        "go",
        # Modern/slang
        "let's go",
        "amped",
        "wired",
        "on one",
        "turnt",
        "hype",
        "beast mode",
        "locked in",
        "in the zone",
        "ready to run",
        "cracked",
        "built different",
        "going hard",
        "no sleep",
        "grinding",
        "on fire",
        "popping off",
        "going crazy",
        "energized",
        "revved up",
        "jacked up",
        "ready to go",
        # Nuanced
        "restless",
        "charged",
        "electric",
        "buzzing",
        "focused",
        "determined",
        "unstoppable",
        "alive",
        "invigorated",
        "can't sit still",
        "need to move",
        "full of energy",
        "wired up",
    ],
    "chill": [
        # Classic relaxation
        "chill",
        "relaxed",
        "calm",
        "peaceful",
        "mellow",
        "laid-back",
        "easy",
        "comfortable",
        "tranquil",
        "serene",
        "zen",
        "smooth",
        # Modern/slang
        "vibing",
        "lowkey",
        "unbothered",
        "no worries",
        "taking it easy",
        "in my zone",
        "just existing",
        "floating",
        "coasting",
        "cruising",
        "easygoing",
        "go with the flow",
        "whatever happens",
        "no stress",
        "all good",
        "it is what it is",
        "taking life slow",
        "no rush",
        "just vibes",
        "relaxing",
        "netflix and chill",
        "lazy day",
        "me time",
        # Nuanced
        "contemplative",
        "meditative",
        "at ease",
        "balanced",
        "centered",
        "quiet",
        "still",
        "grounded",
        "present",
        "mindful",
        "lazy",
        "sleepy",
        "drowsy",
        "lounging",
        "resting",
        "winding down",
        "decompressing",
        "chilling out",
    ],
    "angry": [
        # Classic anger
        "angry",
        "mad",
        "furious",
        "frustrated",
        "annoyed",
        "irritated",
        "pissed",
        "rage",
        "upset",
        "bitter",
        "hostile",
        "aggressive",
        # Modern/slang
        "salty",
        "triggered",
        "livid",
        "heated",
        "over it",
        "done",
        "fed up",
        "can't even",
        "so done",
        "had enough",
        "pissed off",
        "ticked off",
        "steaming",
        "boiling",
        "seeing red",
        "done with this",
        "can't take it",
        "absolute rage",
        "furious",
        "livid af",
        "mad as hell",
        # Nuanced
        "resentful",
        "vindictive",
        "vengeful",
        "indignant",
        "outraged",
        "seething",
        "fuming",
        "irate",
        "wrathful",
        "incensed",
        "burned out",
        "exhausted with",
        "tired of",
        "sick of",
        "at my limit",
        "about to snap",
        "losing it",
    ],
    "nostalgic": [
        "nostalgic",
        "throwback",
        "reminiscing",
        "missing",
        "old times",
        "back then",
        "used to",
        "remember when",
        "those days",
        "bittersweet",
        "wistful",
        "sentimental",
        "thinking of",
        "past",
        "memories",
        "longing",
        "yearning",
        "remembering",
        "the good old days",
        "flashback",
        "reminisce",
        "miss",
        "homesick",
        "pining",
        "looking back",
        "used to be",
        "miss the old days",
        "take me back",
        "simpler times",
        "when things were better",
        "childhood",
        "growing up",
        "wish I could go back",
        "those were the days",
    ],
    "anxious": [
        "anxious",
        "worried",
        "nervous",
        "stressed",
        "overwhelmed",
        "panicking",
        "freaking out",
        "on edge",
        "uneasy",
        "tense",
        "restless",
        "jittery",
        "antsy",
        "spiraling",
        "overthinking",
        "can't relax",
        "mind racing",
        "stressed out",
        "high strung",
        "paranoid",
        "fearful",
        "afraid",
        "scared",
        "terrified",
        "uncomfortable",
        "insecure",
        "uncertain",
        "doubt",
        "concern",
        "freaked",
        "losing my mind",
        "can't breathe",
        "panic attack",
        "anxiety attack",
        "chest tight",
        "hyperventilating",
        "doom scrolling",
        "catastrophizing",
        "what if",
        "rainy day vibes",
        "fireplace",
        "sweater weather",
        "tea and blankets",
        "soft lighting",
        "candlelit",
        "hibernating",
        "nesting",
        "staying in",
    ],
    "cozy": [
        "cozy",
        "comfy",
        "warm",
        "snug",
        "cuddled up",
        "blanket",
        "home",
        "safe",
        "soft",
        "gentle",
        "tender",
        "intimate",
        "wrapped up",
        "nestled",
        "tucked in",
        "hygge",
        "homebody",
        "comfort",
        "snuggled",
        "warm and fuzzy",
        "peaceful",
        "cocoon",
        "sanctuary",
        "haven",
        "sheltered",
        "protected",
    ],
    "melancholic": [
        "melancholic",
        "melancholy",
        "somber",
        "pensive",
        "brooding",
        "dark",
        "gloomy",
        "mournful",
        "sorrowful",
        "forlorn",
        "desolate",
        "bleak",
        "gray",
        "rainy day",
        "heavy",
        "tragic",
        "woeful",
        "doleful",
        "lugubrious",
        "cheerless",
        "dismal",
        "dreary",
        "morose",
        "sullen",
        "glum",
        "existential",
        "questioning everything",
        "life is meaningless",
        "what's the point",
        "empty inside",
        "void",
        "abyss",
        "beautifully sad",
        "tragically beautiful",
        "poetic pain",
    ],
}
