"""add_blend_session_generated_tracks

Revision ID: 00e22e14a638
Revises: 668e123ce0b2
Create Date: 2026-03-03 21:55:42.297211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00e22e14a638'
down_revision: Union[str, Sequence[str], None] = '668e123ce0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blend_sessions', sa.Column('last_generated_json', sa.Text(), nullable=True))
    op.add_column('blend_sessions', sa.Column('last_generated_mood', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blend_sessions', 'last_generated_mood')
    op.drop_column('blend_sessions', 'last_generated_json')
    # ### end Alembic commands ###
