"""Add BlendSession and BlendParticipant

Revision ID: 668e123ce0b2
Revises: c9ba54ff0bb8
Create Date: 2026-03-01 22:15:14.666684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668e123ce0b2'
down_revision: Union[str, Sequence[str], None] = 'c9ba54ff0bb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blend_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('host_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blend_sessions_id'), 'blend_sessions', ['id'], unique=False)
    op.create_table('blend_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['blend_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blend_participants_id'), 'blend_participants', ['id'], unique=False)
    op.create_index(op.f('ix_blend_participants_session_id'), 'blend_participants', ['session_id'], unique=False)
    op.create_index(op.f('ix_blend_participants_user_id'), 'blend_participants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blend_participants_user_id'), table_name='blend_participants')
    op.drop_index(op.f('ix_blend_participants_session_id'), table_name='blend_participants')
    op.drop_index(op.f('ix_blend_participants_id'), table_name='blend_participants')
    op.drop_table('blend_participants')
    op.drop_index(op.f('ix_blend_sessions_id'), table_name='blend_sessions')
    op.drop_table('blend_sessions')
    # ### end Alembic commands ###
