"""drop playlist_id from mood_entries

Revision ID: c9ba54ff0bb8
Revises: cc7d01f5cbeb
Create Date: 2026-03-01 00:19:43.565410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9ba54ff0bb8'
down_revision: Union[str, Sequence[str], None] = 'cc7d01f5cbeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mood_entries', 'playlist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mood_entries', sa.Column('playlist_id', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
